'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FFXIVCraftAMacro.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Advanced_Touch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Advanced Touch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Basic_Synth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Basic Synth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Basic_Touch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Basic Touch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brand_of_Earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brand of Earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brand_of_Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brand of Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brand_of_Ice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brand of Ice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brand_of_Lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brand of Lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brand_of_Water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brand of Water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Brand_of_Wind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brand of Wind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Byregot_s_Blessing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Byregot's Blessing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Careful_Synth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Careful Synth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Careful_Synth_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Careful Synth 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comfort_Zone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comfort Zone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flawless_Synth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flawless Synth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Great_Strides() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Great Strides", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hasty_Touch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hasty Touch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ingenuity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ingenuity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ingenuity_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ingenuity 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Inner_Quiet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inner Quiet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Innovation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Innovation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Manipulation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Manipulation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Master_s_Mend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Master's Mend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Master_s_Mend_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Master's Mend 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Observe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Observe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Piece_by_Piece() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Piece by Piece", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rapid_Synthesis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rapid Synthesis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reclaim() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reclaim", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Rumination() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rumination", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Standard_Synth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standard Synth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Standard_Touch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Standard Touch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Steady_Hand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steady Hand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Steady_Hand_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steady Hand 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Tricks_of_the_Trade() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tricks of the Trade", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Waste_Not() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Waste Not", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Waste_Not_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Waste Not 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
